apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  labels:
    app: udagram-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: udagram-frontend
  type: LoadBalancer
